import "../styles/global.css"
import Naviation from "../components/navigation"

export const metadata = {
  title: {
    template: "%s | Next Movies",
    default: "Loading ...",

  },
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Naviation />
        {children}
      </body>
    </html>
  )
}
