import Naviation from "../../components/navigation";

export const metadata = {
    title: 'About us',
    // description: 'Generated by Next.js',
}

export default function AboutUs() {
    return (<div>
        <h1>About US2</h1>
    </div>
    );
}